# URL base da API externa RAWG ? o RestClient usa isso para saber para onde enviar as requisições HTTP
quarkus.rest-client.rawg-api.url=https://api.rawg.io/api

# Chave de autenticação da API RAWG ? sem ela a API rejeita as requisições
rawg.api.key=3883d4c0e00844e1a855ace2091e025d

# Define o tipo do banco de dados ? H2 é um banco leve que roda em memória, sem precisar instalar nada
quarkus.datasource.db-kind=h2

# Usuário do banco de dados H2
quarkus.datasource.username=admin

# Senha do banco de dados H2
quarkus.datasource.password=admin

# URL de conexão com o banco H2:
# - mem:jogosdb ? banco em memória com o nome "jogosdb"
# - DB_CLOSE_DELAY=-1 ? mantém o banco vivo enquanto a aplicação estiver rodando
# - DB_CLOSE_ON_EXIT=FALSE ? não fecha o banco automaticamente ao encerrar a JVM
quarkus.datasource.jdbc.url=jdbc:h2:mem:jogosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# Define o que o Hibernate faz com as tabelas ao iniciar a aplicação:
# - drop-and-create ? apaga as tabelas existentes e recria do zero a cada restart
# Ideal para desenvolvimento, pois garante que o banco sempre começa limpo
quarkus.hibernate-orm.database.generation=drop-and-create

# Exibe no console todas as queries SQL que o Hibernate executa
# Útil para depuração ? você consegue ver exatamente o que está sendo feito no banco
quarkus.hibernate-orm.log.sql=true