# API EXTERNA RAWG
quarkus.rest-client.rawg-api.url=https://api.rawg.io/api
rawg.api.key=3883d4c0e00844e1a855ace2091e025d


# BANCO DE DADOS ORACLE - FIAP
quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
quarkus.datasource.username=rm567236
quarkus.datasource.password=130106


# HIBERNATE / JPA
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true